week-08/HackLX/api/urls.py
from django.conf.urls import url
from .views import ListOffersView, OfferDetailView, ListCategoriesView, CategoryDetailView


urlpatterns = [
    url(r'offers/$', ListOffersView.as_view(), name='get-offers'),
    url(r'offers/(?P<pk>[0-9]+)/$', OfferDetailView.as_view(), name='offer-detail'),
    url(r'categories/$', ListCategoriesView.as_view(), name = 'get-categories'),
    url(r'categories/(?P<pk>[0-9]+)/$', CategoryDetailView.as_view(), name='category-detail'),

]

week-08/HackLX/hacklx/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'api/', include('api.urls', namespace='url')),
    url(r'', include('website.urls', namespace='website')),
    url(r'api-token-auth/', obtain_jwt_token),
    url(r'api-token-verify/', verify_jwt_token),
    url(r'api-token-refresh/', refresh_jwt_token),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

week-08/HackLX/website/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from .views import get_statistics, RegisterView, CreateOfferView, UpdateOfferView, DeleteOfferView, OfferListView, PendingOffersView, ApprovedAndRejectedOffers, RejectOffer, ApproveOffer



urlpatterns = [
    url(r'^$', OfferListView.as_view(), name='index'),
    url(r'^login/$', login, name='login'),
    url(r'register', RegisterView.as_view(), name='register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^add-offer/$', CreateOfferView.as_view(), name='add-offer'),
    url(r'^offer/edit/(?P<pk>[0-9]+)', UpdateOfferView.as_view(), name='edit-offer'),
    url(r'^delete/(?P<pk>[0-9]+)$', DeleteOfferView.as_view(), name='delete-offer'),
    url(r'^statistics/$', get_statistics, name='statistics'),
    url(r'^offer/pending/$', PendingOffersView.as_view(), name='pending-offers'),
    url(r'^offer/accepted-or-rejected/$', ApprovedAndRejectedOffers.as_view(), name='approved-or-rejected-offers'),
    url(r'offer/approve/(?P<pk>[0-9]+)/$', ApproveOffer.as_view(), name='approve-offer'),
    url(r'offer/reject/(?P<pk>[0-9]+)/$', RejectOffer.as_view(), name='reject-offer'),

]

week-08/HackLX/website/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.__repr__()


class Offer(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    category = models.ForeignKey(Category)
    author = models.ForeignKey(User)

    image = models.ImageField(null=True, blank=True)

    # choices kinda weird..
    choices = models.CharField(max_length=8, choices=(('A','approved'), ('P', 'pending'), ('R', 'rejected')), default=('A'))

week-08/HackLX/website/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Offer


# class OfferCreateModelForm(forms.ModelForm):
#     class Meta:
#         model = Offer
#         fields = ('title', 'description', 'category', 'image')

class RegisterModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        help_texts = {
                'username': ''
                }


class CreateOfferModelForm(forms.ModelForm):
    class Meta:
        model = Offer
        # exclude = ['author']
        fields = ('title', 'description', 'category', 'image')
        # fields = '__all__'


class UpdateOfferModelForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['title', 'description', 'category', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].required = False

week-08/HackLX/website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from .forms import CreateOfferModelForm, RegisterModelForm, UpdateOfferModelForm
from .mixins import LoginRequiredMixin, UserCanUpdateOrDeleteOfferMixin, SuperUserRequiredMixin
from .models import Offer, Category



class RegisterView(FormView):

    template_name = 'registration/registration.html'
    form_class = RegisterModelForm
    success_url = reverse_lazy('website:login')

    def form_valid(self, form):
        User.objects.create_user(username=form.data['username'], password=form.data['password'])
        return super().form_valid(form)

class CreateOfferView(LoginRequiredMixin, CreateView):
    model = Offer
    template_name = 'website/add_offer.html'
    form_class = CreateOfferModelForm
    success_url = reverse_lazy('website:index')


    def form_valid(self, form):
        # offer = form.save(commit=False)
        # offer.author = self.request.user

        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateOfferView(LoginRequiredMixin, UserCanUpdateOrDeleteOfferMixin, UpdateView):
    model = Offer
    form_class = UpdateOfferModelForm
    template_name = 'website/add_offer.html'
    success_url = reverse_lazy('website:index')


class DeleteOfferView(LoginRequiredMixin, UserCanUpdateOrDeleteOfferMixin, DeleteView):
    model = Offer
    template_name = 'website/index.html'
    success_url = reverse_lazy('website:index')

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        storage, path = self.object.image.storage, self.object.image.path
        storage.delete(path)
        return super().delete(*args, **kwargs)


class ApproveOffer(LoginRequiredMixin,SuperUserRequiredMixin, RedirectView):
    url = reverse_lazy('website:pending-offers')

    def get(self, *args, **kwargs):
        offer = get_object_or_404(Offer,id=kwargs['pk'])
        offer.choices = 'approved'
        offer.save()
        return super().get(*args, **kwargs)


class RejectOffer(LoginRequiredMixin, SuperUserRequiredMixin, RedirectView):
    url = reverse_lazy('website:pending-offers')

    def get(self, *args, **kwargs):
        offer = get_object_or_404(Offer,id=kwargs['pk'])
        offer.choices = 'rejected'
        offer.save()
        # Delete offer image
        storage, path = offer.image.storage, offer.image.path
        storage.delete(path)
        return super().get(*args, **kwargs)


class OfferListView(ListView):
    model = Offer
    template_name = 'website/index.html'
    paginate_by = 5
    queryset = Offer.objects.order_by('created_at').reverse().filter(choices='A')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['object_list'].select_related('author', 'category').all()
        return context


class PendingOffersView(ListView):
    model = Offer
    template_name = 'website/pending_offers.html'
    queryset = Offer.objects.filter(choices='pending')


class ApprovedAndRejectedOffers(ListView):
    model = Offer
    template_name = 'website/index.html'
    queryset = Offer.objects.filter(Q(choices='approved') | Q(choices='rejected'))


def get_statistics(request):
    # TODO: Move logic in services
    categories = Category.objects.all()
    categories_result = {}

    for category in categories:
        categories_result[category.name] = category.offer_set.count()


    # TODO: Add more statistics information

    return render(request, 'website/statistics.html', locals())

week-08/HackLX/templates/website/add_offer.html
{% extends "website/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<form method="POST" enctype="multipart/form-data" action="">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" value="Submit">
</form>
{% endblock %}

week-08/HackLX/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HackLX</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'website:index' %}">HackLX</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              {# <li class="active"><a href="{% url 'website:index' %}">Home</a></li> #}
              {# <li><a href="#about">About</a></li> #}
            <li><a href="/add-offer/">Add Offer</a></li>
            <li><a href="/statistics/">Statistics</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
            <li><a href="{% url 'website:login' %}">Login</a></li>
            <li><a href="{% url 'website:register' %}">Register</a></li>
            {% else %}
            <li><a href="/logout/">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
    {% block content %}

    {% endblock content %}
    </div> <!-- /container -->

  </body>
</html>

week-08/HackLX/templates/website/index.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% for offer in object_list %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            {% if offer.image %}
                <img src="{{ offer.image.url }}" width="300">
            {% endif %}
        </div>
        <div class="col-md-6">
            Title: {{ offer.title }} </br>
            Category: {{ offer.category.name }} </br>
            Author: {{ offer.author }} </br>
            From: {{ offer.created_at }} </br>
            Description: {{ offer.description }} </br>
            {# Status: {{ offer.choices.1 }} </br> #}
        </div>
        <div class="col-md-2">
            {% if offer.author == request.user or request.user.is_superuser %}
            <form method="GET" enctype="multipart/form-data" action="{% url 'website:edit-offer' offer.id %}">
                <button class="btn btn-warning" type="submit">Редактирай</button>
            </form>
            </br>
            <form method="POST" enctype="multipart/form-data" action="{% url 'website:delete-offer' offer.id %}">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Изтрий </button>
            </form>
            <br>

            {% endif %}
            {% block manage_choice %}
            {% endblock %}
        </div>
    </div>
</div>
{% endfor %}

{# Probably the easiest implementation of pagination ever #}
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}
{% endblock content %}

week-08/HackLX/templates/website/pending_offers.html
{% extends "website/index.html" %}
{% load crispy_forms_tags %}

{% block manage_choice %}
{% if request.user.is_superuser and offer.choices == 'pending' %}
<form method="GET" action="{% url 'website:approve-offer' offer.id %}">
    <button class="btn btn-success" type="submit">Одобри </button>
</form>
<br>

<form method="GET" action="{% url 'website:reject-offer' offer.id %}">
    <button class="btn btn-danger" type="submit">Отхвърли </button>
</form>
{% endif %}

{% endblock %}

week-08/HackLX/templates/website/statistics.html
{% extends "website/base.html" %}

{% block content %}
    <div class="jumbotron">
    <h2>Top categories: </h2>
      {% for category, count in categories_result.items %}
        {{ category }}: {{ count }} </br>
      {% endfor %}
    </div>
{% endblock content %}